Base structure implementation
ajax-tarnavskyi-m/BookExchangeService pull request #1
Opened 2024-08-15 15:42 UTC by ajax-tarnavskyi-m

2024-08-15 20:53 UTC, ajax-gnatiuk-s requested changes
Good work!

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on docker-compose.yml
> +      - 27017:27017
```suggestion
      - 27017:27017

```

Please, add new line. Also, it's the good idea to setup your IDE to make it automatically
See https://stackoverflow.com/a/16761228

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/BookController.kt
> +import org.springframework.web.bind.annotation.*
It's better to keep all imports explicitly instead of `*`

![image](https://github.com/user-attachments/assets/4f192547-e56c-4ec0-be65-5c4d661d3433)

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/BookController.kt
> +class BookController(val bookService: BookService) {
```suggestion
class BookController(private val bookService: BookService) {
```
?

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/BookController.kt
> +    fun increaseAmount(@PathVariable("id") id: String, @RequestParam addition: Int = 1): Int {
```suggestion
    fun increaseAmount(
        @PathVariable("id") id: String, 
        @RequestParam(defaultValue = "1") addition: Int 
    ): Int {
```

Reformatting is optional, but as for me the suggested approach is easier to read.

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/BookController.kt
> +    @PatchMapping("/{id}/increase-amount")
AFAIK verb in path is not recommended. Please, google it.

Seems, you we can create `update`-like endpoint with PatchMapping

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/BookController.kt
> +    //TODO validate that 'addition' is positive
👍

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/book/ResponseBookDto.kt
> +)
```suggestion
)

```
please, fix all places

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    fun addBookToWishList(@PathVariable("id") userId: String, @RequestParam bookId: String) : Boolean {
```suggestion
    fun addBookToWishList(@PathVariable("id") userId: String, @RequestParam bookId: String): Boolean {
```

----

Let's create a separate PR with applying [detekt plugin](https://github.com/detekt/detekt),
also create `gradle.properties` file with the following content:
```
kotlin.code.style=official
```

So, before commiting your code you can validate codestyle:
```bash
./gradlew detekt
```

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    @PatchMapping("/{id}/wishlist")
should it be in a separate controller?

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    @PatchMapping("/{id}/wishlist")
Why: here we have user operations, but the wishlist sounds like a separate sub-domain

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/book/BookMapper.kt
> +    }
```suggestion
    fun Book.toDto() = ResponseBookDto(
            id,
            title,
            description,
            yearOfPublishing,
            amazonPrice,
            amountAvailable
    )
```
(formatting should be fixed in the suggestion)

1. The function is pretty simple and the return type is obvious. So in this case we can omit explicit return type
2. `this` is redundant

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/book/RequestBookDto.kt
> +    val yearOfPublishing: Int?,
why this property is nullable?

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/book/RequestBookDto.kt
> +    val amountAvailable: Int
```suggestion
    val amountAvailable: Int,
```

It's best practice to add trailing comma

See https://www.baeldung.com/kotlin/trailing-comma-support#the-benefits-of-the-trailing-comma-support

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/book/ResponseBookDto.kt
> +    val id: String?,
Seems, the Id cannot be null

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/book/ResponseBookDto.kt
> +    val amountAvailable: Int?
Please, make nullable properties only in cases when it really could contain `null`.

From business perspective `id`, `title`, `price` and `amountAvailable` cannot be null. But we can discuss it offline in case I am wrong.

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/book/ResponseBookDto.kt
> +    val amazonPrice: Double?,
What if in future we add some another shop in addition to `amazon`? Extra property?
I don't force you to change something right now, but think about it.

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/user/RequestUserDto.kt
> +    val contact: String?,
what is contact?

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/user/RequestUserDto.kt
> +    val bookWishList: MutableSet<Int>?
```suggestion
    val bookWishList: Set<Int>?
```
Why `Int`?

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/user/ResponseUserDto.kt
> +    val bookWishList: MutableSet<Int>?
```suggestion
    val bookWishList: Set<Int>?
```

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/model/User.kt
> +    val bookWishList: MutableSet<Int>? = mutableSetOf()
I think we can use `Set` instead of `MutableSet` here

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/repository/UserRepository.kt
> +}
```suggestion
interface UserRepository : MongoRepository <User, String>
```

It's Kotlin 😉

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +class BookService(val bookRepository: BookRepository) {
```suggestion
class BookService(private val bookRepository: BookRepository) {
```

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        return bookRepository.findByIdOrNull(bookId) ?: throw Exception("No book with id = $bookId")
```suggestion
        return bookRepository.findByIdOrNull(bookId) ?: throw BookNotFoundException("No book with id = $bookId")
```
Prefer using custom exceptions

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        return bookRepository.save(book)
Prefer non-reversed conditions. It's easier to read
```suggestion
        return if (bookRepository.existsById(bookId)) {
            book.id = bookId
            bookRepository.save(book)
        } else {
            throw BookNotFoundException("No book with id = $bookId, to update")
        }
```

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +            TODO("event for subscribers")
```suggestion
            println("Some meaningful message here")
```

For now, it's ok providing a dummy logic. In your approach an exception will be thrown.

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/resources/application.properties
> +spring.data.mongodb.database=myDatabase
please, use `yaml` instead of `properties`.
We are the serious developers :)

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +class UserService(val userRepository: UserRepository) {
```suggestion
class UserService(private val userRepository: UserRepository) {
```

2024-08-15 20:53 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/service/EventService.kt
> +//        val subscribers = userRepository.findAllWhereWishListContainsWithId(bookId);
commiting a commented code is bad practice

2024-08-16 11:10 UTC, ajax-shulepa-a requested changes

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/exception/BookNotFoundException.kt
> +) : Exception("Book with id=$bookId does not found while trying to perform $actionDescription")
```suggestion
) : RuntimeException("Book with id=$bookId does not found while trying to perform $actionDescription")
```

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/exception/UserNotFoundException.kt
> +) : Exception("User with id=$userId does not found while trying to perform $actionDescription")
```suggestion
) : RuntimeException("User with id=$userId does not found while trying to perform $actionDescription")
```

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/dto/user/UserMapper.kt
> +            this.bookWishList
[nit] this can be omitted in Kotlin
```suggestion
           login,
           contact,
           bookWishList
```

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    }
[nit] in Kotlin you can use shorter syntax
https://kotlinlang.org/docs/functions.html#single-expression-functions
```suggestion
    fun getById(@PathVariable("id") userId: String): ResponseUserDto =
       userService.getById(userId).toDto()
```

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/model/User.kt
> +}
add empty line

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +    }
good example of single expression function

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +    fun update(bookId: String, book: Book): Book {
Why can't it be just book with an initialized ID?

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        val updatedAmount: Int = (book.amountAvailable ?: 0) + addition
in general no need to specify type for local variable
```suggestion
        val updatedAmount = (book.amountAvailable ?: 0) + addition
```

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +            .apply { this.id = id }
It's very strange to me that you're setting id to model that was returned from DB

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +            println("Message for subscribers of book (id=$id) was sent")
it's better to use some logging lib

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        if (bookRepository.existsById(bookId)) {
IMO this method can be idempotent. if a user is trying to delete an already deleted entity - we can respond with success

2024-08-16 11:10 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +    }
same comment about idempotent function

2024-08-16 14:24 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    fun addBookToWishList(@PathVariable("id") userId: String, @RequestParam bookId: String) : Boolean {
Okay, i will create a separate PR with detekt, after merging this one

2024-08-16 14:34 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    @PatchMapping("/{id}/wishlist")
From my perspective, a partial update of a user’s wishlist is more of a “user operation”. In general, in which scenario is it a good idea to create a separate controller for a subdomain?

2024-08-16 14:48 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/book/RequestBookDto.kt
> +    val yearOfPublishing: Int?,
I will fix that

2024-08-16 14:50 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/book/ResponseBookDto.kt
> +    val amountAvailable: Int?
I will fix that

2024-08-16 15:16 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/book/ResponseBookDto.kt
> +    val amazonPrice: Double?,
The purpose of this property is to track the minimum acceptable price for books that a user can use for book exchanges. We rely on Amazon for tracking book prices because it offers a sufficiently wide collection of world literature.

2024-08-16 15:19 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/user/RequestUserDto.kt
> +    val contact: String?,
It was supposed to be a piece of information indicating where Kafka should be configured. I think it’s better to remove it for now.

2024-08-16 15:23 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/user/RequestUserDto.kt
> +    val bookWishList: MutableSet<Int>?
Mistake. It will be better to make a Set<String> for ids, or Set<Book>? (I am not sure how mongo handles such cases)

2024-08-16 15:25 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/user/RequestUserDto.kt
> +    val bookWishList: MutableSet<Int>?
Mistake. Should be String

2024-08-19 06:23 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    @PatchMapping("/{id}/wishlist")
why this thread was resolved?

2024-08-19 06:26 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    @PatchMapping("/{id}/wishlist")
> a partial update of a user’s wishlist is more of a “user operation”.

I suppose, we will have much more operations over the wishlist. So, it sounds like a separate subdomain

2024-08-19 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/book/BookMapper.kt
> +
```suggestion

```

2024-08-19 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/book/ResponseBookDto.kt
> +    val amazonPrice: Double?,
let's discuss offline, after the daily

2024-08-19 13:37 UTC, ajax-tarnavskyi-m commented on docker-compose.yml
> +      - 27017:27017
Fixed: Added new lines for all files, and updated IDE settings

2024-08-19 13:38 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/controller/BookController.kt
> +import org.springframework.web.bind.annotation.*
Fixed: Updated code and IDE settings

2024-08-19 13:38 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/controller/BookController.kt
> +class BookController(val bookService: BookService) {
Fixed: Investigated private properties meaning and updated all properties in constructors

2024-08-19 13:54 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/controller/BookController.kt
> +    fun increaseAmount(@PathVariable("id") id: String, @RequestParam addition: Int = 1): Int {
Fixed: Reformated code as proposed

2024-08-19 13:54 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/controller/BookController.kt
> +    @PatchMapping("/{id}/increase-amount")
Fixed: Runamed uri as "/{id}/amount"

2024-08-19 13:56 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/book/ResponseBookDto.kt
> +)
Fixed: added new line at the end of all files

2024-08-19 14:07 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    @PatchMapping("/{id}/wishlist")
So, are you proposing to make `Whishlist(val bookId: String, val userId: String) `a separate entity, or should it be used as part of the User entity?

2024-08-19 14:07 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/book/BookMapper.kt
> +    }
Fixed: Updated as proposed

2024-08-19 14:08 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/book/RequestBookDto.kt
> +    val yearOfPublishing: Int?,
Fixed: Changed `yearOfPublishing` field to `non nullable`

2024-08-19 14:10 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/book/RequestBookDto.kt
> +    val amountAvailable: Int
Fixed: I investigated the subject and improved the code.

2024-08-19 14:11 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/book/ResponseBookDto.kt
> +    val id: String?,
Fixed: True. I corrected type of Id to `non nullable`

2024-08-19 14:22 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/user/ResponseUserDto.kt
> +    val bookWishList: MutableSet<Int>?
Fixed: Updated as suggested

2024-08-19 14:23 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/model/User.kt
> +    val bookWishList: MutableSet<Int>? = mutableSetOf()
Fixed: updated as suggested

2024-08-19 14:24 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +class BookService(val bookRepository: BookRepository) {
Fixed: Investigated private properties meaning and updated all properties in constructors

2024-08-19 14:24 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        return bookRepository.findByIdOrNull(bookId) ?: throw Exception("No book with id = $bookId")
Fixed: Implemented custom exceptions

2024-08-19 14:25 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        return bookRepository.save(book)
Fixed: Investegated code conventions and updated code as suggested

2024-08-19 14:25 UTC, ajax-tarnavskyi-m commented on src/main/resources/application.properties
> +spring.data.mongodb.database=myDatabase
Fixed: Reformat file as suggested

2024-08-19 14:25 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +class UserService(val userRepository: UserRepository) {
Fixed: Investigated private properties meaning and updated all properties in constructors

2024-08-19 14:26 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/exception/BookNotFoundException.kt
> +) : Exception("Book with id=$bookId does not found while trying to perform $actionDescription")
Fixed: Implemented custom exceptions for this purpose

2024-08-19 14:26 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/exception/UserNotFoundException.kt
> +) : Exception("User with id=$userId does not found while trying to perform $actionDescription")
Fixed: Implemented custom exceptions for this purpose

2024-08-19 14:27 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/user/UserMapper.kt
> +            this.bookWishList
Fixed: updated as suggested

2024-08-19 14:28 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    }
Fixed: Investigated code conventions and updated as suggested

2024-08-19 14:28 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +    }
Fixed: Investigated code conventions and changed to expression function

2024-08-19 14:29 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/model/User.kt
> +}
Fixed: added empty line at the end of the file

2024-08-19 14:32 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +    fun update(bookId: String, book: Book): Book {
No reason. Both approaches are valid for me. Should I change it?

2024-08-19 14:34 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +            .apply { this.id = id }
I agree, but It seems that the .copy method is not copying the entity ID.

2024-08-19 14:51 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/book/BookMapper.kt
> +
Fixed: updated as suggested

2024-08-19 14:52 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +    }
Fixed: I made delete methods idempotent

2024-08-19 14:52 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        if (bookRepository.existsById(bookId)) {
Fixed: I made delete methods idempotent

2024-08-19 14:52 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +            println("Message for subscribers of book (id=$id) was sent")
Fixed: Changed to logger.info invocation

2024-08-19 20:55 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    @PatchMapping("/{id}/wishlist")
Just for now, we can move the endpoint into a separate controller, that's it.
Let's refactor later

2024-08-19 20:56 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    @PatchMapping("/{id}/wishlist")
Actually, we can keep the endpoint here. Just keep in mind moving to a separate controller when more operations over the wishlist will appear

2024-08-19 21:03 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/exception/UserNotFoundException.kt
> +) : Exception("User with id=$userId does not found while trying to perform $actionDescription")
but it wasn't fixed as Andriy suggested

2024-08-19 21:04 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +    }
As I can see, nothing has been changed in the code

2024-08-19 21:11 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +        userRepository.deleteById(userId)
Suppose we have the next case:
0. No such user `id=1` in the DB
1. `Thread 1`: invokes the function
2. `Thread 1`: checks the user `id=1` doesn't exist and logs the message
3. `Thread 2`: created the user `id=1`
4. `Thread 1`: deletes the user `id=1` (line 37)

I don't expect that the `thread 1` delete the user.


the simple fix 

```suggestion
        if (userRepository.existsById(userId)) {
            userRepository.deleteById(userId)
        } else {
            logger.warn { "Attempting to delete absent user with id=$userId" }
        }
```

The suggestion is not ideal and still has issues. But we can improve it what when we will start learning mongo

2024-08-19 21:12 UTC, ajax-gnatiuk-s reviewed
good job, let's fix the rest of comments

2024-08-20 07:34 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/controller/UserController.kt
> +    @PatchMapping("/{id}/wishlist")
Okay i will keep in mind. Thanks for revue

2024-08-20 07:36 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/exception/UserNotFoundException.kt
> +) : Exception("User with id=$userId does not found while trying to perform $actionDescription")
I agree. I meant thats part of code was improved

2024-08-20 07:49 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +        userRepository.deleteById(userId)
Thx, i see the problem now. 
Fixed: Corrected code as suggested

2024-08-20 11:34 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +    }
Missed that. Fixed now

2024-08-20 11:45 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/dto/user/RequestUserDto.kt
> +    val bookWishList: Set<String>?,
what is difference between empty set and null set in your case?

2024-08-20 11:45 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/exception/UserNotFoundException.kt
> +) : Exception("User with id=$userId does not found while trying to perform $actionDescription")
My point was to extend your custom exceptions from RuntimeException. I don't really understand what was fixed)

2024-08-20 11:45 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/model/User.kt
> +    val bookWishList: Set<String>? = mutableSetOf(),
```suggestion
    val bookWishList: Set<String>? = setOf(),
```

2024-08-20 11:45 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
>      fun getById(bookId: String): Book {
this is also single-expression function

2024-08-20 11:45 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        if (bookRepository.existsById(bookId)) {
Do you really need to track that object that exists?  I propose to skip this check

2024-08-20 11:45 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +    fun update(bookId: String, book: Book): Book {
yes, please

2024-08-20 11:45 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +            .apply { this.id = id }
think how you can fix your class so that Id will copy

2024-08-20 11:46 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +    }
do you really need to check existence?

2024-08-20 13:58 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        if (bookRepository.existsById(bookId)) {
It seems like a good idea to track how often we try to delete absent entities. 
I will remove this logic if you insist

2024-08-20 14:58 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/user/RequestUserDto.kt
> +    val bookWishList: Set<String>?,
I think emptySet will be better in this scenario. Thanks for idea. I will fix that

2024-08-20 15:15 UTC, ajax-shulepa-a requested changes
Final changes :)

2024-08-20 15:15 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/dto/book/RequestCreateBookDto.kt
> +data class RequestCreateBookDto(
```suggestion
data class CreateBookRequest(
```
Dto doesn't have any semantic value here

2024-08-20 15:15 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/dto/book/RequestUpdateBookDto.kt
> +data class RequestUpdateBookDto(
```suggestion
data class UpdateBookRequest(
```
fix all similar places

2024-08-20 15:15 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/exception/MappingNullValueException.kt
> +) : Exception("Cant map null value for $fieldName filed of $modelName model")
```suggestion
) : RuntimeException("Cant map null value for $fieldName filed of $modelName model")
```

2024-08-20 15:15 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        if (bookRepository.existsById(bookId)) {
What triggers me is 2 requests over the network when you can have one

check docs if you can omit existsById and still track deleting absent entities
https://github.com/spring-projects/spring-data-mongodb/blob/main/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/MongoOperations.java#L1759

2024-08-20 15:20 UTC, ajax-shulepa-a commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        if (bookRepository.existsById(bookId)) {
btw you can omit existsById in your 'update' method as well. but you can leave it for time when you'll be studying mongo

2024-08-20 15:50 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/BookService.kt
> +        if (bookRepository.existsById(bookId)) {
It’s an interesting approach, but I don’t see how I can retrieve the delete result at the moment. I’ll keep this in mind and plan to implement it when I start learning MongoDB scripts.

2024-08-20 18:14 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +    private val logger = KotlinLogging.logger {}
seems, the logger should be declared in companion object.

2024-08-20 18:15 UTC, ajax-gnatiuk-s approved these changes

2024-08-21 07:14 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +    private val logger = KotlinLogging.logger {}
Fixed: Extracted loggers into companion object for each Service

2024-08-21 08:25 UTC, ajax-shulepa-a approved these changes

2024-08-21 11:00 UTC, merged