Adding nats and protobuf
ajax-tarnavskyi-m/BookExchangeService pull request #11
Opened 2024-10-22 15:59 UTC by ajax-tarnavskyi-m

2024-10-23 11:05 UTC, ajax-torbin-v commented on core/src/main/kotlin/pet/project/core/exception/handler/GlobalExceptionHandler.kt
Why GlobalExceptionHandler in core module?

2024-10-23 11:05 UTC, ajax-torbin-v commented on domain-service/src/main/kotlin/pet/project/app/mapper/UserControllerMapper.kt
> +            it.addAllBookWishList(bookWishList)
Make code more kotlinish
```suggestion
            it.id = id
            it.email - email
            it.login = login
            it.addAllBookWishList(bookWishList)
```

2024-10-23 11:05 UTC, ajax-torbin-v commented on domain-service/src/test/kotlin/pet/project/app/controller/nats/UserNatsControllerTest.kt
Why have you decided to use Unit tests?

2024-10-23 11:05 UTC, ajax-torbin-v commented on domain-service/src/test/kotlin/pet/project/app/mapper/UserControllerMapperTest.kt
> +        assertEquals(exampleDomainUser.bookWishList.toList(), protoUser.bookWishListList)
Can you just compare full objects?

2024-10-23 11:05 UTC, ajax-torbin-v commented on domain-service/src/test/kotlin/pet/project/app/mapper/UserThrowableMapperTest.kt
> +    }
Pls use @ParameterizedTest for this

2024-10-23 11:05 UTC, ajax-torbin-v commented on gateway/src/main/kotlin/pet/project/gateway/mapper/UserResponseProtoMapper.kt
> +            }
This should be extracted info separate function

2024-10-23 11:05 UTC, ajax-torbin-v commented on gateway/src/main/kotlin/pet/project/gateway/rest/UserController.kt
> +            "${UserNatsSubject.PREFIX}.${UserNatsSubject.CREATE}",
Why do we need to recreate this string for every request?

2024-10-23 11:05 UTC, ajax-torbin-v commented on gateway/src/test/kotlin/pet/project/gateway/mapper/UserRequestProtoMapperTest.kt
> +        assertNotNull(request.bookWishList)
Provide message for assertNotNull

2024-10-23 11:05 UTC, ajax-torbin-v commented on internal-api/src/main/proto/pet/project/internal/commonmodels/user/user.proto
> +  optional string id = 1;
Id can't be optional here
Imagine returning User from a db without id

2024-10-23 11:05 UTC, ajax-torbin-v commented on internal-api/src/main/kotlin/pet/project/internal/app/subject/UserNatsSubject.kt
> +}
Make all subjects in one place, so user will be acknowledged about capabilities of your API

2024-10-23 11:05 UTC, ajax-torbin-v commented on internal-api/src/main/proto/pet/project/internal/input/reqreply/user/add_book_to_wish_list.proto
> +package pet.project.internal.input.reqreply.user.add_book_to_wish_list;
```suggestion
package pet.project.internal.input.reqreply.user;
```

2024-10-23 11:05 UTC, ajax-torbin-v commented on internal-api/src/main/proto/pet/project/internal/input/reqreply/user/update.proto
> +  }
Why do you need nested message with 1 field?

2024-10-23 11:12 UTC, ajax-marchenko-s commented on domain-service/src/main/kotlin/pet/project/app/mapper/UserRepositoryMapper.kt
> +@Component
not needed

2024-10-23 11:12 UTC, ajax-marchenko-s commented on domain-service/src/main/kotlin/pet/project/app/mapper/UserRepositoryMapper.kt
> +        if (login != "") update.set(MongoUser::login.name, login)
maybe `.isBlank()`?

2024-10-23 11:12 UTC, ajax-marchenko-s commented on gateway/src/test/kotlin/pet/project/gateway/rest/UserControllerTest.kt
> +            .uri("/user")
create const for `/user`

2024-10-23 11:20 UTC, ajax-yurkovskyi-t commented on domain-service/src/test/kotlin/pet/project/app/controller/nats/UserNatsControllerTest.kt
> +class UserNatsControllerTest {
rewrite to integration tests

2024-10-23 11:20 UTC, ajax-yurkovskyi-t commented on domain-service/src/test/kotlin/pet/project/app/mapper/UserRepositoryMapperTest.kt
> +        val wishList = listOf("5f8d0d55b54764421b7156c7", "5f8d0d55b54764421b7156c8")
why dont use ObjectId()?

2024-10-23 11:20 UTC, ajax-yurkovskyi-t commented on gateway/src/test/kotlin/pet/project/gateway/rest/UserControllerTest.kt
> +            .uri("/user")
make /user constant

2024-10-23 11:20 UTC, ajax-yurkovskyi-t commented on gateway/src/test/kotlin/pet/project/gateway/rest/UserControllerTest.kt
> +            .expectBody(UserExternalResponse::class.java)
exceptBody<>

2024-10-23 11:20 UTC, ajax-yurkovskyi-t commented on gateway/src/test/kotlin/pet/project/gateway/rest/UserControllerTest.kt
> +        val bookId = "66bf6bf8039339103054e21a"
ObjectId()?

2024-10-23 11:32 UTC, ajax-tarnavskyi-m commented on core/src/main/kotlin/pet/project/core/exception/handler/GlobalExceptionHandler.kt
Because i use both for `gateway.UserController` and `domain-service.BookController`

2024-10-23 11:51 UTC, ajax-tarnavskyi-m commented on internal-api/src/main/proto/pet/project/internal/input/reqreply/user/update.proto
> +  }
Lets discus it on daily

2024-10-23 11:54 UTC, ajax-tarnavskyi-m commented on gateway/src/test/kotlin/pet/project/gateway/rest/UserControllerTest.kt
> +            .uri("/user")
I prefer to use literal here

2024-10-23 12:53 UTC, ajax-tarnavskyi-m commented on gateway/src/test/kotlin/pet/project/gateway/rest/UserControllerTest.kt
> +            .uri("/user")
I prefer to use literal here

2024-10-24 08:29 UTC, ajax-tarnavskyi-m commented on domain-service/src/test/kotlin/pet/project/app/mapper/UserThrowableMapperTest.kt
> +    }
Although it’s possible to use parameterized tests in this case, I believe it’s not entirely appropriate. We only have 2-3 test scenarios, and creating methods that store arguments would complicate the test structure and reduce readability.

2024-10-24 13:50 UTC, ajax-shulepa-a requested changes

2024-10-24 13:50 UTC, ajax-shulepa-a commented on gateway/src/main/kotlin/pet/project/gateway/mapper/UserRequestMapper.kt
> +            setEmail(request.email)
1. why do you need  'apply' here if you're using setters?
2. Does this break 'patch' logic?

2024-10-24 13:50 UTC, ajax-shulepa-a commented on internal-api/src/main/kotlin/pet/project/internal/app/subject/NatsSubject.kt
> +        const val PREFIX = "user"
make it private

2024-10-24 13:50 UTC, ajax-shulepa-a commented on domain-service/src/main/kotlin/pet/project/app/mapper/UserResponseMapper.kt
> +            .also { it.successBuilder }
```suggestion
            .apply { successBuilder }
```

keep same code style, in this class I see different styles for same cases

2024-10-24 13:50 UTC, ajax-shulepa-a commented on domain-service/src/main/kotlin/pet/project/app/annotation/NatsController.kt
> +    val subjectPrefix: String = "",
how do you use this parameter?

2024-10-24 13:50 UTC, ajax-shulepa-a commented on domain-service/src/main/kotlin/pet/project/app/processor/NatsSubscriptionAnnotationBeanPostProcessor.kt
> +    }
what was the motivation to put subscribing logic here?

2024-10-24 13:50 UTC, ajax-shulepa-a commented on domain-service/src/main/kotlin/pet/project/app/processor/NatsSubscriptionAnnotationBeanPostProcessor.kt
> +                val request = getParser(handlerMethod).parseFrom(message.data)
will the parser change from request to request? why do you need to use reflection each time?

2024-10-24 13:50 UTC, ajax-shulepa-a commented on domain-service/src/main/kotlin/pet/project/app/processor/NatsSubscriptionAnnotationBeanPostProcessor.kt
> +    private fun buildErrorResponse(handlerMethod: Method, exception: Throwable): GeneratedMessage {
use Descriptor logic, please

2024-10-24 13:50 UTC, ajax-shulepa-a commented on domain-service/src/test/kotlin/pet/project/app/controller/nats/UserNatsControllerIntegrationTest.kt
> +    )
use randomized entities, please

2024-10-24 13:50 UTC, ajax-shulepa-a commented on domain-service/src/test/kotlin/pet/project/app/mapper/UserResponseMapperTest.kt
> +        val response = toAddBookToUserWishListResponse()
when you name the method "toSomething" it means that you have a context that you want to convert to something. here I don't see any context, so fix the method name

2024-10-24 13:50 UTC, ajax-shulepa-a commented on gateway/src/test/kotlin/pet/project/gateway/rest/UserNatsControllerValidationTest.kt
> +class UserNatsControllerValidationTest {
do you test nats controller here?

2024-10-24 15:15 UTC, ajax-tarnavskyi-m commented on domain-service/src/main/kotlin/pet/project/app/processor/NatsSubscriptionAnnotationBeanPostProcessor.kt
> +    }
I will extract login in separate method

2024-10-24 15:25 UTC, ajax-tarnavskyi-m commented on domain-service/src/main/kotlin/pet/project/app/annotation/NatsController.kt
> +    val subjectPrefix: String = "",
This is an optional parameter that can be used to define a subject prefix for all handlers (similar to @RequestMapping("/path") in REST).

The `NatsSubscriptionAnnotationBeanPostProcessor` will check if the `subjectPrefix` exists and append it to each handler’s subject.

2024-10-24 15:53 UTC, ajax-tarnavskyi-m commented on gateway/src/main/kotlin/pet/project/gateway/mapper/UserRequestMapper.kt
> +            setEmail(request.email)
Yep, there is NullPointerException on partial update attempt. I will fix that and add test for partial update.

2024-10-27 08:16 UTC, ajax-tarnavskyi-m commented on domain-service/src/test/kotlin/pet/project/app/controller/nats/UserNatsControllerIntegrationTest.kt
> +    )
I added fixture to create random fields

2024-10-29 07:35 UTC, ajax-shulepa-a commented on domain-service/src/main/kotlin/pet/project/app/config/NatsConfig.kt
> +    @Value("\${nats.connection-uri:nats://localhost:4222}")
here it's better to not specify a default value, instead force to define it for every profile/running configuration as URL may change

2024-10-29 07:35 UTC, ajax-shulepa-a commented on domain-service/src/main/kotlin/pet/project/app/processor/NatsSubscriptionAnnotationBeanPostProcessor.kt
> +    }
my question was about postProcessBeforeInitialization method. why subscribing logic is there?

2024-10-29 08:09 UTC, ajax-shulepa-a commented on core/src/testFixtures/kotlin/pet/project/core/RandomTestFields.kt
> +object RandomTestFields {
these fields are random only between different runs of test. it's better to have random value on each property access

2024-10-29 08:09 UTC, ajax-shulepa-a commented on domain-service/src/main/kotlin/pet/project/app/annotation/NatsController.kt
> +    val subjectPrefix: String = "",
As I see, this parameter is not used in your handlers

2024-10-29 08:48 UTC, ajax-tarnavskyi-m commented on domain-service/src/main/kotlin/pet/project/app/processor/NatsSubscriptionAnnotationBeanPostProcessor.kt
> +    }
Because we are not modifying the bean, but rather modifying the dispatcher, it does not violate the contract to use subscribing logic in the postProcessBeforeInitialization method. The main reason I don’t use the postProcessAfterInitialization method is that otherwise I would need to check for the existence of the NatsController annotation recursively, because we might be given a proxy instead of the ‘original’ bean.

2024-10-29 08:52 UTC, ajax-tarnavskyi-m commented on domain-service/src/main/kotlin/pet/project/app/annotation/NatsController.kt
> +    val subjectPrefix: String = "",
I will delete it

2024-10-30 12:56 UTC, ajax-shulepa-a approved these changes

2024-10-30 12:59 UTC, merged