Added deployment for gateway and domain-service
ajax-tarnavskyi-m/BookExchangeService pull request #12
Opened 2024-10-30 13:06 UTC by ajax-tarnavskyi-m

Updated ingress. Added Dockerfiles for subprojects. Added config map for NATS

2024-10-31 07:06 UTC, ajax-gnatiuk-s requested changes

2024-10-31 07:06 UTC, ajax-gnatiuk-s commented on Dockerfile
> +CMD ["java", "-jar", "domain-service.jar"]
we have two services in the same docker image.
It's definitely bad practice. Build two separate images

2024-10-31 07:06 UTC, ajax-gnatiuk-s commented on docker-compose.yml
> +      dockerfile: Dockerfile
the dockerfile contains two services inside, pls see the prev comment

2024-11-04 08:37 UTC, ajax-shulepa-a approved these changes

2024-11-04 12:00 UTC, ajax-gnatiuk-s approved these changes

2024-11-04 12:01 UTC, merged