Adding profiling post processor. Updating readme.md file
ajax-tarnavskyi-m/BookExchangeService pull request #4
Opened 2024-08-23 12:21 UTC by ajax-tarnavskyi-m

2024-08-26 14:43 UTC, ajax-marchenko-s reviewed
Good work!

2024-08-26 14:43 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +    fun create(user: User): User = this.userRepository.save(user)
remove `this`

2024-08-26 14:43 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +        return this.userRepository.save(updatedUser)
remove `this`

2024-08-26 14:43 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +            return this.userRepository.save(user)
remove `this`

2024-08-26 14:43 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/service/UserService.kt
> +        if (this.userRepository.existsById(user.id!!.toHexString())) {
remove `this`

2024-08-26 14:44 UTC, ajax-yurkovskyi-t commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +@Configuration
add space here

2024-08-26 14:44 UTC, ajax-yurkovskyi-t commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +        }
we can replace here manual null check

2024-08-26 14:44 UTC, ajax-yurkovskyi-t commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +
u can use any to simplify this

2024-08-26 14:52 UTC, ajax-yurkovskyi-t commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +        return super.postProcessBeforeInitialization(bean, beanName)
change to return bean

2024-08-26 14:52 UTC, ajax-yurkovskyi-t commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +            return super.postProcessAfterInitialization(bean, beanName)
change to return bean

2024-08-26 14:54 UTC, ajax-yurkovskyi-t commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +    }
forgot private here

2024-08-26 15:00 UTC, ajax-yurkovskyi-t commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +    }
map { it.type.jvmErasure.java }

2024-08-26 15:07 UTC, ajax-yurkovskyi-t commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +    private var map = hashMapOf<String, KClass<out Any>>()
change to val and give a better name

2024-08-26 15:19 UTC, ajax-yurkovskyi-t commented on src/main/kotlin/pet/project/app/dto/book/BookMapper.kt
> +class BookMapper {
Why did you decide to change from an object to a class?

2024-08-26 19:08 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/dto/book/BookMapper.kt
> +class BookMapper {
Because of `@Component`?

2024-08-26 19:11 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +        private val logger = KotlinLogging.logger {}
pls, use standard Slf4J instead of unclear kotlin's logger

2024-08-26 19:11 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +        val invokeSuper: Any? = proxy.invokeSuper(obj, args ?: emptyArray())
Pls, ask Nikita to review this function

2024-08-27 07:11 UTC, ajax-malov-n commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +        logger.info { "${obj::class.simpleName}.${method.name} ran for ${after - before} nano" }
Never inline parameters into log message

✅ correct:
```kotlin
val s = ""
logger.info("Logging parameter={} using message pattern",s)

```

2024-08-27 07:11 UTC, ajax-malov-n commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +        val invokeSuper: Any? = proxy.invokeSuper(obj, args ?: emptyArray())
What if the function throws an exception? Do you want to catch it? Do you want to profile the function even if the function throws an exception?

2024-08-27 07:11 UTC, ajax-malov-n commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +    private fun withProfiling(obj: Any, method: Method, args: Array<out Any>?, proxy: MethodProxy): Any? {
Prefer to write a lot of arguments from top to bottom
```kotlin
 private fun withProfiling(
        obj: Any,
        method: Method,
        args: Array<out Any>?,
        proxy: MethodProxy,
    ): Any?
```

2024-08-28 06:34 UTC, ajax-gnatiuk-s requested changes

2024-08-28 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +
```suggestion
```

2024-08-28 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +@Configuration
why configuration? Maybe `@Component` would be more suitable

2024-08-28 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +            log.info("{}.{} ran for {} nano", obj::class.simpleName, method.name, after - before)
**[NIT](https://josipmisko.com/posts/code-review-nit)**

```suggestion
            log.info("{}.{} ran for {} ns", obj::class.simpleName, method.name, after - before)
```

2024-08-28 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/annotation/Profiling.kt
> +annotation class Profiling
so, we profile all methods in class if the annotation is present?

What about private methods? Do we profile them as well?

2024-08-28 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +        constructorParams.forEach { log.info("constructor param: {}", it) }
logging in loop is bad practice. Please, log params in the next way:
```suggestion
        log.info("constructor params: {}", constructorParams.contentToString())
```

2024-08-28 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +        constructorParams.forEach { log.info("constructor param: {}", it) }
By the way, do we really need to log the parameters?

2024-08-28 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +        propertyValues.forEach { log.info("property value: {}, type: {}", it, it?.javaClass?.name) }
the same as in prev comment

2024-08-28 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +        return enhancer.create(constructorParams, propertyValues)
let's talk after the daily about this function.
Just want to find out what the problem do we solve here

2024-08-28 06:34 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +class ProfilingAnnotationBeanPostProcessor : BeanPostProcessor {
It would be awesome to have some tests

2024-08-28 07:53 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessor.kt
> +            log.info("{}.{} ran for {} nano", obj::class.simpleName, method.name, after - before)
Interesting article

2024-08-28 07:55 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/annotation/Profiling.kt
> +annotation class Profiling
Yes, we profile them as well

2024-08-30 08:51 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/profiling/LoggingProfilingConsumer.kt
> +
```suggestion
```

2024-08-30 08:51 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/profiling/LoggingProfilingConsumer.kt
> +package pet.project.app.util.profiling
`util` is not suitable package for beans

2024-08-30 08:51 UTC, ajax-gnatiuk-s commented on build.gradle.kts
> +
```suggestion
```

2024-08-30 08:51 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/profiling/LoggingProfilingConsumer.kt
> +    override fun accept(message: String) {
```suggestion
    override fun consume(data: ProfilingData) {
```
where `ProfilingData`:
```kotlin
data class ProfilingData(
    method: String,
    duration: Duration,
) 
```

2024-08-30 08:51 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/util/profiling/ProfilingAnnotationBeanPostProcessor.kt
> +    class ProfilingInvocationHandler(
private?

2024-08-30 08:51 UTC, ajax-gnatiuk-s commented on src/test/kotlin/pet/project/app/util/ProfilingAnnotationBeanPostProcessorTest.kt
> +    }
```suggestion
```

use instead:

```
@ExtendWith(MockKExtension::class)
class ProfilingAnnotationBeanPostProcessorTest
```

2024-08-30 11:36 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/profiling/LoggingProfilingConsumer.kt
> +        log.info("$className.$methodName method ran for $nanoseconds ns")
inlined parameters

2024-08-30 11:36 UTC, ajax-gnatiuk-s commented on src/test/kotlin/pet/project/app/profiling/ProfilingAnnotationBeanPostProcessorTest.kt
> +        if (result == null) fail("Should not return null value from afterInit method")
`if` in test method is bad practice.

 u can assert not null instead

2024-08-30 11:36 UTC, ajax-gnatiuk-s commented on src/test/kotlin/pet/project/app/profiling/ProfilingAnnotationBeanPostProcessorTest.kt
> +        (profilingProxy as ProxyRequiredInterface).testMethod()
`when` section _must_ contain only one action.

what we test here `postProcessAfterInitialization` or `testMethod`?

2024-08-30 11:46 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/annotation/Profiling.kt
> +annotation class Profiling
are u sure?

2024-09-02 08:32 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/profiling/ProfilingAnnotationBeanPostProcessor.kt
> +    class LoggerProfilingMethodInterceptor(private val profilingConsumer: ProfilingConsumer) : MethodInterceptor {
```suggestion
    private class LoggerProfilingMethodInterceptor(private val profilingConsumer: ProfilingConsumer) : MethodInterceptor {
```

2024-09-02 08:32 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/profiling/ProfilingAnnotationBeanPostProcessor.kt
> +        if (beanClass.annotations.contains(Profiling())) {
```suggestion
        if (beanClass.annotations.any { it is Profiling }) {
```

2024-09-02 08:32 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/profiling/ProfilingAnnotationBeanPostProcessor.kt
> +        if (beanClass.annotations.contains(Profiling())) {
creating a new instance looks wierd to me.

2024-09-02 08:32 UTC, ajax-gnatiuk-s commented on src/main/kotlin/pet/project/app/profiling/ProfilingAnnotationBeanPostProcessor.kt
> +            factory.proxy
```suggestion
            ProxyFactory(bean)
                 .apply { addAdvice(profilingInterceptor) }
                 .proxy
```

2024-09-02 11:49 UTC, ajax-gnatiuk-s approved these changes

2024-09-02 14:09 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/annotation/Profiling.kt
> +annotation class Profiling
For me it is better to profile all methods. It may have some advantages if will try to find bottle necks in some code with a lot of private methods

2024-09-02 14:10 UTC, merged