Adding tests, validation, and tests for validation
ajax-tarnavskyi-m/BookExchangeService pull request #5
Opened 2024-09-03 10:31 UTC by ajax-tarnavskyi-m

2024-09-03 11:26 UTC, ajax-samondros-b requested changes

2024-09-03 11:26 UTC, ajax-samondros-b commented on src/main/kotlin/pet/project/app/dto/book/CreateBookRequest.kt
> +    @field:Range(min = 1600, max = 2024, message = "Publish year of book should be in valid range")
looks like your bounds are not valid

2024-09-03 11:26 UTC, ajax-samondros-b commented on src/main/kotlin/pet/project/app/dto/book/CreateBookRequest.kt
>      val price: Double,
BigDecimal

2024-09-03 11:26 UTC, ajax-samondros-b commented on src/main/kotlin/pet/project/app/dto/book/UpdateBookRequest.kt
>      val yearOfPublishing: Int,
same about valid bounds

2024-09-03 11:26 UTC, ajax-samondros-b commented on src/main/kotlin/pet/project/app/validation/ValidObjectId.kt
> +    val message: String = "Invalid OpenID format",
OpenID?

2024-09-03 11:26 UTC, ajax-samondros-b commented on src/test/kotlin/pet/project/app/controller/BookControllerValidationTest.kt
> +            .andExpect(status().isBadRequest)
please assert error message. Applicable to other tests

2024-09-03 11:33 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/dto/book/CreateBookRequest.kt
> +    @field:Range(min = 1600, max = 2024, message = "Publish year of book should be in valid range")
What do you mean?

2024-09-05 07:53 UTC, ajax-samondros-b approved these changes

2024-09-05 08:09 UTC, merged