Adding docker and k8s
ajax-tarnavskyi-m/BookExchangeService pull request #8
Opened 2024-09-18 13:39 UTC by ajax-tarnavskyi-m

2024-09-18 13:45 UTC, ajax-malov-n commented on src/main/resources/application.yml
> +      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=admin
```suggestion
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=admin
```

2024-09-18 13:48 UTC, ajax-yurkovskyi-t reviewed
Good job!

2024-09-18 13:48 UTC, ajax-yurkovskyi-t commented on docker-compose.yml
> +        MONGO_DB_NAME: book_x_db
why dont use env?

2024-09-18 13:48 UTC, ajax-yurkovskyi-t commented on k8s/mongo-pvc.yaml
> +
redundant line

2024-09-18 14:01 UTC, ajax-marchenko-s reviewed
Great job!

2024-09-18 14:01 UTC, ajax-marchenko-s commented on .github/workflows/gradle-build.yml
> +      - name: Perform Delta coverage
Minor: You could add `continue-on-error: ${{ contains(github.event.pull_request.labels.*.name, 'suppress-delta-coverage') }}`, so if your PR is labeled with suppress-delta-coverage, the build process will succeed even if the delta coverage check fails (you might need this in future PRs).

2024-09-18 14:01 UTC, ajax-marchenko-s commented on .github/workflows/gradle-build.yml
> +    branches: [ main ]
use the same style for `branches`

2024-09-18 14:01 UTC, ajax-marchenko-s commented on docker-compose.yml
>        MONGO_INITDB_ROOT_PASSWORD: root
you could add .env for this info instead of writing inside docker-compose

2024-09-18 14:01 UTC, ajax-marchenko-s commented on k8s/book-x-app.yaml
> +              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
think about creating configmap to store value

2024-09-19 10:27 UTC, ajax-tarnavskyi-m commented on k8s/book-x-app.yaml
> +              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
Thank you for the suggestion! I considered the idea of creating a ConfigMap to store the values, but I decided that i don’t need the debug options in the main development branch. These options are primarily for local debugging, so I’m removing them from this PR.

2024-09-19 11:08 UTC, ajax-gnatiuk-s requested changes

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on .gitignore
> +config/detekt/detekt.yml
why exclude this file?

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on .gitignore
> +.env
why exclude this file?

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on .github/workflows/gradle-build.yml
> +          java-version: 17
why 17?
Maybe it's time to support something newer?

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on .github/workflows/gradle-build.yml
> +        run: ./gradlew build --scan -x deltaCoverage
what about adding `--parallel`?

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on .github/workflows/gradle-build.yml
> +        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
```suggestion
        if: ${{ !cancelled() }}
```
It's the good idea to publish the test results always

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on docker-compose.yml
> +    image: book-exchange-service
let's build from dockerfile?

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on docker-compose.yml
> +  spring-app:
```suggestion
 app:
```

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on docker-compose.yml
> +  never_gona_let_you_down:
it's smart, but let's give the volumes some meaningful names

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on k8s/book-x-app.yaml
> +  replicas: 1
lets' have more than 1 replicas

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on k8s/book-x-app.yaml
> +          image: book-exchange-service
let's specify concrete version of the image

2024-09-19 11:08 UTC, ajax-gnatiuk-s commented on k8s/mongo.yaml
> +        - name: k8s-pv
```suggestion
        - name: mongo-data-volume
```

2024-09-19 14:37 UTC, ajax-tarnavskyi-m commented on .github/workflows/gradle-build.yml
> +          java-version: 17
Why do you think we should use java 21?

2024-09-19 14:43 UTC, ajax-tarnavskyi-m commented on .github/workflows/gradle-build.yml
> +        run: ./gradlew build --scan -x deltaCoverage
I don’t think this is a good idea because our current build process involves sequential execution where tasks depend on each other. The --parallel flag is beneficial when tasks are independent and can be executed concurrently, which is not the case here.

2024-09-19 14:44 UTC, ajax-tarnavskyi-m commented on .gitignore
> +.env
I prefer not to expose environment variables in a public repository.

2024-09-19 14:47 UTC, ajax-tarnavskyi-m commented on docker-compose.yml
> +  spring-app:
It’s easier for me to identify my application by using ‘spring-app’ instead of just ‘app’.

2024-09-19 14:57 UTC, ajax-tarnavskyi-m commented on k8s/mongo.yaml
> +        - name: k8s-pv
Is it a good idea to name our PV this way? What if we decide to use it for something else in the future?

2024-09-19 15:00 UTC, ajax-tarnavskyi-m commented on .gitignore
> +config/detekt/detekt.yml
Good point. Added it to commit

2024-09-20 08:40 UTC, ajax-gnatiuk-s commented on .github/workflows/gradle-build.yml
> +          java-version: 17
discussed offline. migrate to 21

2024-09-20 08:40 UTC, ajax-gnatiuk-s commented on .github/workflows/gradle-build.yml
> +        run: ./gradlew build --scan -x deltaCoverage
discussed offline

2024-09-20 08:40 UTC, ajax-gnatiuk-s commented on .gitignore
> +.env
there are no secrete data inside

2024-09-20 08:40 UTC, ajax-gnatiuk-s commented on docker-compose.yml
> +  spring-app:
discussed offline

2024-09-20 08:41 UTC, ajax-gnatiuk-s commented on k8s/mongo.yaml
> +        - name: k8s-pv
discussed offline

2024-09-20 11:24 UTC, ajax-gnatiuk-s approved these changes

2024-09-20 12:48 UTC, merged