Mongo repository implementation
ajax-tarnavskyi-m/BookExchangeService pull request #9
Opened 2024-10-03 11:24 UTC by ajax-tarnavskyi-m

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/test/kotlin/pet/project/app/service/impl/UserServiceImplTest.kt
> +        val fooLogger: Logger = LoggerFactory.getLogger(UserServiceImpl::class.java) as Logger
```suggestion
        val logger: Logger = LoggerFactory.getLogger(UserServiceImpl::class.java) as Logger
```

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +        return mongoTemplate.findById(id, Book::class.java)
```suggestion
    override fun findById(id: String): Book? {
        return mongoTemplate.findById(id, Book::class.java)
```

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/dto/user/UpdateUserRequest.kt
>  )
What if i want to perform partial update?

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/model/Book.kt
> +    }
We need to make all fields of nullable type in mongo model

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/controller/UserController.kt
NO_CONTENT returns content?)

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +    }
We should return updated object

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +    override fun setShouldBeNotified(bookId: String, boolValue: Boolean): Long {
Very confusing naming
What is boolValue, btw?

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +    private fun withAmountUpdatePipeline(delta: Int): AggregationUpdate {
Move private functions to the EOF

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +        val ifAmountWasZero = Cond.`when`(valueOf("\$amountAvailable").equalToValue(delta))
```suggestion
        val amountCond = Cond.`when`(valueOf("\$amountAvailable").equalToValue(delta))
```

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +    override fun updateAmountMany(requests: List<UpdateAmountRequest>): Int {
Why Int here, not Long?

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +        return mongoTemplate.updateFirst<Book>(query, withAmountUpdatePipeline(request.delta)).modifiedCount
Here we should also return book with updated amount

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +            query.addCriteria(where("amountAvailable").gte(positiveDelta))
```suggestion
            query.addCriteria(where("amountAvailable").lte(delta))
```

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +    }
We shouldn't notify user even if nothing was deleted

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/UserMongoRepository.kt
> +                field("bookDetails")
Why you don't just use default lookup?
Your local field will be _id

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/UserMongoRepository.kt
> +            match(where("bookWishList").`is`(ObjectId(bookId))),
Use isEqualTo

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/UserMongoRepository.kt
> +    override fun findAllBookListSubscribers(booksIds: List<String>): List<UserNotificationDetails> {
Can't get from name, what are we looking for here
For all book, list or subscribers?

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/service/impl/BookServiceImpl.kt
> +            log.warn("Affected {} documents while trying to delete book with id={}", deleteCount, bookId)
When it's possible that you will delete more then 1 book by id?
deleteCount will be always 0
Why warn level?

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/service/impl/NotificationServiceImpl.kt
> +            else -> userRepository.findAllBookListSubscribers(bookIdsForNotification)
Why do we need 2 separate methods for 1 element and list?
When we need to check for 1 element, we can always call listOf()
Also, if you pass empty list, you will get also empty list

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/test/kotlin/pet/project/app/controller/BookControllerValidationTest.kt
> +        assertEquals("Delta value must not be zero", response.invalidInputReports[0].message)
You probably need to just use "andExpect" in result

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/test/kotlin/pet/project/app/controller/BookControllerValidationTest.kt
> +        assertEquals(1, response.invalidInputReports.size)
What is 1?
🧙 number

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/test/kotlin/pet/project/app/repository/BookRepositoryTest.kt
> +        assertTrue(actual.id != null, "Id should not be null after insert!")
// GIVEN ?

```suggestion
        assertNotNull(actual.id, "Id should not be null after insert!")
```

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/test/kotlin/pet/project/app/repository/BookRepositoryTest.kt
> +        val expected = savedBook.amountAvailable + 5
This is not THEN, it's GIVEN

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/test/kotlin/pet/project/app/repository/BookRepositoryTest.kt
> +        assertEquals(2, secondUpdatedBook.amountAvailable, "Book 2 amountAvailable should be updated correctly")
🧙 🔮 numbers

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/test/kotlin/pet/project/app/repository/BookRepositoryTest.kt
> +            UpdateAmountRequest(secondSavedBook.id.toString(), -10)  // This will fail
```suggestion
            UpdateAmountRequest(secondSavedBook.id.toString(), -10)
```

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/test/kotlin/pet/project/app/repository/UserRepositoryTest.kt
> +        assertNotNull(actualUser)
Pls provide message for assertNotNull/assertNull...

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/test/kotlin/pet/project/app/repository/UserRepositoryTest.kt
> +        )
Lots of duplicated code
Move it ti testFixture

2024-10-03 13:03 UTC, ajax-torbin-v commented on src/test/kotlin/pet/project/app/service/impl/BookServiceImplTest.kt
> +    fun `check update amount throws exception when insufficient books`() {
Pls stick to one test naming
Either start from "check" or from "sholud"

2024-10-03 13:08 UTC, ajax-butriy-v commented on src/main/kotlin/pet/project/app/repository/BookRepository.kt
> +    fun setShouldBeNotified(bookId: String, boolValue: Boolean): Long
rename to **updateShouldBeNotified**, because **set** is confusing a bit

2024-10-03 13:08 UTC, ajax-butriy-v commented on src/main/kotlin/pet/project/app/config/DatabaseChangeLog.kt
> +            .any { it.getString("name") == INDEX_NAME }
you can use something like that:

```suggestion
        val indexExists = mongoTemplate.indexOps<User>().indexInfo
                  .map { it.name }
                  .any { it == INDEX_NAME }
```

2024-10-03 13:08 UTC, ajax-butriy-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +        val query = query(where("_id").isEqualTo(bookId))
move `query(where("_id").isEqualTo(bookId))` to a separate function (you have duplicated this line at least several times)

2024-10-03 13:08 UTC, ajax-butriy-v commented on src/main/kotlin/pet/project/app/service/impl/BookServiceImpl.kt
>          }
🤯 🤯 🤯 

I suggest using findAndModify() which returns T?, if t is nullable, you can throw you NotFound exception

2024-10-03 13:08 UTC, ajax-butriy-v commented on src/main/kotlin/pet/project/app/service/impl/BookServiceImpl.kt
> +        return true
You don`t need to check if list is not empty 

```suggestion
    override fun exchangeBooks(requests: List<UpdateAmountRequest>): Boolean {
        val matchedCount = bookRepository.updateAmountMany(requests)
        if (matchedCount != requests.size) {
            throw IllegalArgumentException("Requested books absent or have less amount available that needed: $requests")
        }

        requests.filter { it.delta > 0 }
            .map { it.bookId }
            .let { notificationService.notifySubscribedUsers(it) }

        return true
```

2024-10-03 13:08 UTC, ajax-butriy-v commented on src/test/kotlin/pet/project/app/service/impl/UserServiceImplTest.kt
> +        //WHEN
btw, add detert-formatting, because there are some issues in your project:
<img width="394" alt="image" src="https://github.com/user-attachments/assets/f9f70d0e-f097-48d5-9e06-1862bc2907a8">

2024-10-03 13:40 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/model/User.kt
>  data class User(
add `@TypeAlias`

2024-10-03 13:40 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +        return mongoTemplate.exists<Book>(query(where("_id").isEqualTo(id)))
replace `_id` with `Fields.UNDERSCORE_ID`

2024-10-03 13:40 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/repository/impl/UserMongoRepository.kt
> +            match(where("bookWishList").`is`(ObjectId(bookId))),
user field name from model instead of general string

2024-10-03 13:40 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/repository/impl/UserMongoRepository.kt
> +                "book",
use collection name from model

2024-10-03 13:40 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/service/impl/BookServiceImpl.kt
> +    private val notificationService: NotificationService
add comma

2024-10-03 13:40 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +    override fun updateAmount(request: UpdateAmountRequest): Long {
this method would always return 1 or 0
change to boolean

2024-10-03 13:40 UTC, ajax-marchenko-s commented on src/main/kotlin/pet/project/app/service/impl/BookServiceImpl.kt
> +        if (updatedDocumentsCount != 1L) {
think about changing repo method returning

2024-10-03 13:40 UTC, ajax-marchenko-s commented on src/test/kotlin/pet/project/app/service/impl/UserServiceImplTest.kt
> +open class UserServiceImplTest {
why this class should be open?

2024-10-03 13:44 UTC, ajax-marchenko-s commented on src/test/kotlin/pet/project/app/service/impl/UserServiceImplTest.kt
> +        val expected = User(ObjectId("66c35b050da7b9523070cb3a"), "testUser123", "test.user@example.com", dummyWishlist)
```suggestion
        val expected = User(ObjectId(testRequestUserId), "testUser123", "test.user@example.com", dummyWishlist)
```

2024-10-03 13:48 UTC, ajax-marchenko-s commented on src/test/kotlin/pet/project/app/service/impl/NotificationServiceImplTest.kt
> +        every { bookRepository.setShouldBeNotified("66faafae1d7c375ad3c2ab2d", false) } returns 0L
```suggestion
        every { bookRepository.setShouldBeNotified(bookIds.get(0), false) } returns 0L
```

2024-10-03 13:55 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +    override fun updateAmount(request: UpdateAmountRequest): Long {
We should not return 1/0 or Boolean here, imho

2024-10-03 14:43 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/impl/BookServiceImpl.kt
> +        return true
In this part, we are passing a List<String> instead of a String. I’ll rewrite this code to improve clarity.

2024-10-03 15:09 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/impl/BookServiceImpl.kt
> +            log.warn("Affected {} documents while trying to delete book with id={}", deleteCount, bookId)
Thanks, i will change condition to `deleteCount == 1L`
Logging the deletion of a non-existing user is unexpected behavior. However, if it does occur, having clear logs will make it easier to identify and troubleshoot the issue quickly.

2024-10-03 15:32 UTC, ajax-tarnavskyi-m commented on src/test/kotlin/pet/project/app/repository/UserRepositoryTest.kt
> +        )
I improved code readability

2024-10-03 15:34 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +        val ifAmountWasZero = Cond.`when`(valueOf("\$amountAvailable").equalToValue(delta))
I disagree – this suggestion reduces code readability.

2024-10-03 15:41 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +    override fun updateAmountMany(requests: List<UpdateAmountRequest>): Int {
We return matchedCount here because it provides additional information compared to modifiedCount, which is the return value used in other methods.

2024-10-03 15:46 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +            query.addCriteria(where("amountAvailable").gte(positiveDelta))
I disagree—if the received delta is negative, the suggested condition will never be true.

2024-10-03 15:47 UTC, ajax-torbin-v commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +        val ifAmountWasZero = Cond.`when`(valueOf("\$amountAvailable").equalToValue(delta))
Okay, but name ifAmountWasZero suggests doesn't correspond with checking equality between current amount and delta

2024-10-03 15:51 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +    }
We’re getting feedback from the database about user deletion. I think it’s helpful to know when attempts are made to delete users that don’t exist because that shouldn’t happen according to the business logic.

2024-10-03 16:03 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/repository/impl/UserMongoRepository.kt
> +                field("bookDetails")
Because we need to match `book._id` with the `ObjectId(bookId)` which is passed as a parameter to the method

2024-10-03 16:03 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/repository/impl/BookMongoRepository.kt
> +    private fun withAmountUpdatePipeline(delta: Int): AggregationUpdate {
It’s a common practice to place private methods below the public methods that call them for better code readability and organization.

2024-10-08 08:08 UTC, ajax-samondros-b commented on src/main/kotlin/pet/project/app/config/DatabaseChangeLog.kt
> +class DatabaseChangeLog {
should be covered by IT test

2024-10-08 08:09 UTC, ajax-samondros-b requested changes
add test for migration and give not so common name for it

2024-10-08 08:30 UTC, ajax-tarnavskyi-m commented on src/main/kotlin/pet/project/app/service/impl/NotificationServiceImpl.kt
> +            else -> userRepository.findAllBookListSubscribers(bookIdsForNotification)
The method for handling a single element is already used by another endpoint, so we can simplify the aggregation when dealing with a list containing only one element.

2024-10-08 08:46 UTC, ajax-tarnavskyi-m commented on src/test/kotlin/pet/project/app/repository/BookRepositoryTest.kt
> +        val expected = savedBook.amountAvailable + 5
I don't agree

2024-10-08 08:47 UTC, ajax-tarnavskyi-m commented on src/test/kotlin/pet/project/app/controller/BookControllerValidationTest.kt
> +        assertEquals("Delta value must not be zero", response.invalidInputReports[0].message)
I’m already parsing the response to perform other assertions, so using andExpect in the WHEN block wouldn’t add value compared to handling it in the THEN block

2024-10-09 09:02 UTC, ajax-samondros-b approved these changes

2024-10-10 14:06 UTC, merged